//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.SpotifyControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double ControllerLeft {
            get {
                return ((double)(this["ControllerLeft"]));
            }
            set {
                this["ControllerLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ControllerTop {
            get {
                return ((double)(this["ControllerTop"]));
            }
            set {
                this["ControllerTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CG.SpotifyControl.Metadata.Resolvers.WebServicesResolver")]
        public string MetadataResolver {
            get {
                return ((string)(this["MetadataResolver"]));
            }
            set {
                this["MetadataResolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpotifyLibResolverOptionsUsername {
            get {
                return ((string)(this["SpotifyLibResolverOptionsUsername"]));
            }
            set {
                this["SpotifyLibResolverOptionsUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpotifyLibResolverOptionsPassword {
            get {
                return ((string)(this["SpotifyLibResolverOptionsPassword"]));
            }
            set {
                this["SpotifyLibResolverOptionsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebServicesResolverOptionsProxyAddress {
            get {
                return ((string)(this["WebServicesResolverOptionsProxyAddress"]));
            }
            set {
                this["WebServicesResolverOptionsProxyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort WebServicesResolverOptionsProxyPort {
            get {
                return ((ushort)(this["WebServicesResolverOptionsProxyPort"]));
            }
            set {
                this["WebServicesResolverOptionsProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
	public CG.SpotifyControl.Metadata.Resolvers.eProxyType WebServicesResolverOptionsProxyType
	{
            get {
		    return ((CG.SpotifyControl.Metadata.Resolvers.eProxyType)(this["WebServicesResolverOptionsProxyType"]));
            }
            set {
                this["WebServicesResolverOptionsProxyType"] = value;
            }
        }
    }
}
